config/routes.rb
 Prototype::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => 'tasks#index'
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :sessions => "users/sessions", registrations: "users/registrations" }
  

  resources :projects
  resources :tasks do
    get '/start_task' => "tasks#start", :as => :start_task
    get '/finish_task' => "tasks#finish", :as => :finish_task

    
    resources :interruptions
    post '/interruptions' => "interruptions#create", :as => :create_interruption
    get  '/interruptions_stop'=> "interruptions#stop_interruption", :as => :stop_interruption
  end   
  get '/state_task' => "tasks#state", :as => :state_task
  delete '/trash_task' => "tasks#trash", :as => :trash_task
  get '/reload_month' => "tasks#reload_month", :as => :reload_month
  get '/reload_tree' => "tasks#reload_tree", :as => :reload_tree
  

   
   resources :nodes do
    collection do
      get :manage

      post :rebuild
    end
   end 

end

app/models/task.rb
class Task < Node
  include ActiveModel::ForbiddenAttributesProtection
  has_many :interruptions
  validates :task_name, :action, presence: true

  state_machine :state, :initial => :to_do do
    
    event :activate do
      transition [:to_do, :paused, :expired] => :active
    end
    
    event :finish do
      transition [:active] => :finished
    end

    event :pause do
      transition [:active] => :paused
    end

    event :expire do
      transition [:active] => :expired
    end

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TheSortableTreeController::Rebuild
  def index
    @interruption = Interruption.new 
    @nodes = current_user.nodes
    @task = Task.new
    @project = Project.new
    @filter = params[:filter].present? ? Filter.new(params[:filter]) : Filter.new
    @calendar_nodes = current_user.tasks.where('start_time is not NULL')
    @date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
    state_filte    
    by_gtd_state
    gon.total_unproductive_time = current_user.unproductive_time
    gon.total_productive_time = current_user.total_time - current_user.unproductive_time

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @parent = current_user.projects.first
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end


  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    if @task.save 
      flash[:notice] = 'Task successfully created'
    else
      flash[:alert] = 'Please review your data'
    end
    redirect_to tasks_path
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update_attributes(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Node.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path}
      format.json { head :no_content }
    end
    
  end

  def trash
    @nodes = current_user.nodes.where(action: "Trash" )
    @nodes.each do |n| 
      n.destroy
    end  
    respond_to do |format|
      format.html { redirect_to "http://localhost:3000/tasks?key=trash" }
      format.json { head :no_content }
    end
  end  

  def start
     current_user.tasks.find(params[:task_id]).activate!
     render json: true
  end 

  def finish 
    #TODO: chequear interrup 
    @task = current_user.tasks.find(params[:task_id])
    @task.finish_time = Time.now
    @task.finish!
    unproductive_time = 0
    @task.interruptions.each do |interruption|
      unproductive_time = unproductive_time + interruption.duration  
    end    
    current_user.unproductive_time += unproductive_time
    current_user.total_time += (@task.finish_time - @task.start_time)
    current_user.save
    render json: true
  end 

  def by_gtd_state
    @nodes = @nodes.where(action: params[:key].capitalize) if params[:key]
  end
   
  def state
    node = current_user.nodes.find(params[:task_id])
    node_old_action = node.action.downcase
    if node.type == 'Task'
      node.update_attribute(:action, params[:key].capitalize) if params[:key]
    else
      node.update_attribute(:action, params[:key].capitalize) if params[:key]  
    end
    render json: { old_action: node_old_action, new_action: node.action.downcase }
  end

  def reload_month
    @date = Date.parse(params[:month].gsub('-', '/')) 
    @calendar_nodes = current_user.tasks.where('start_time is not NULL') 
    render partial: 'calendar' 
  end

  def reload_tree
    @nodes = current_user.nodes
    state_filte   
    by_gtd_state
    render partial: 'tree'
  end  
  
  def state_filte
    if params[:filter].present?
        # prueba
        if params[:filter][:search] != ""
          @nodes = current_user.tasks.where(task_name: params[:filter][:search])  
        end
        if params[:filter][:state] == "to_do"
          @nodes = current_user.tasks.where(state: params[:filter][:state])
        end  

        if params[:filter][:state]== "paused" 
            @nodes = current_user.tasks.where(state: params[:filter][:state])
        end  
        if params[:filter][:state]== "finished"
          @nodes = current_user.tasks.where(state: params[:filter][:state])
        end  
      end  
    end  
  private

  def task_params
    params.require(:task).permit(:task_name,:estimated_time, :due_date, :note, :priority, :parent_id, :action, :start_time)
  end   
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_calendar.html.haml
%h2#month
  = link_to "<", '#', data: { month: (@date.beginning_of_month - 1).strftime("%Y-%m") }, class: 'previous'
  = h @date.strftime("%B %Y") 
  = link_to ">", '#', data: { month: (@date.end_of_month + 1).strftime("%Y-%m") }, class: 'next'
= calendar_for @calendar_nodes, :year => @date.year, :month => @date.month do |calendar| 
  = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
  = calendar.day(:day_method => :start_time )  do |date, nodes| 
    = date.day
    %ul
      - for node in nodes 
        %li
          = link_to 'X', node, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tags'
          = link_to h(node.task_name), node, class: 'tags'

app/views/tasks/_form.html.haml
.modal.hide.fade#NewtaskModal
  .modal-header
    %button.close.cabe(data-dismiss="modal" aria-hidden="true") &times
    %h1 New task
  .modal-body
    = simple_form_for(@task) do |f| 
      - if @task.errors.any? 
        #error_explanation
          %h2
            = pluralize(@task.errors.count, "error") 
            prohibited this task from being saved:

          %ul
          - @task.errors.full_messages.each do |msg| 
            %li= msg 
      .field= f.input :task_name 
      .field= f.input :estimated_time 
      .field= f.input :start_time 
      .field= f.input :due_date 
      .field= f.input :priority 
      
      .field= f.input :note 
      .field= f.input :action, priority: [ "Inbox" ], collection: [ "Inbox", "Next", "Project", "Waiting", "Someday"], :include_blank => false
      
      %div= f.select :parent_id, nested_set_options(current_user.projects, nil, method: :type, value: 'Task') {|i| "#{'-' * i.level} #{i.project_title}"  if i.type == 'Project' } 
      .modal-footer  
        .actions= f.submit  

app/views/tasks/_tree.html.haml
= sortable_tree @nodes  

app/views/tasks/edit.html.haml
.header-edit 
  %h2 Editing task
.thumbnail
  .caption
    = simple_form_for(@task) do |f| 
      .field= f.input :task_name 
      .field= f.input :estimated_time 
      .field= f.input :start_time 
      .field= f.input :due_date 
      .field= f.input :priority 
      .field= f.input :note 
      .field= f.input :action, priority: [ "Inbox" ], collection: [ "Inbox", "Next", "Project", "Waiting", "Someday"], :include_blank => false 
      %div= f.select :parent_id, nested_set_options(current_user.projects, nil, method: :type, value: 'Task') {|i| "#{'-' * i.level} #{i.project_title}"  if i.type == 'Project' } 
      .actions= f.submit  

= link_to 'Show', @task  |
= link_to 'Back', tasks_path 

app/views/tasks/index.html.haml
.row-fluid
  %ul#thumbnails
    %li.span3.pull-left.sidebar
      .content
        .divider
        .my-profile 
          - if current_user.avatar.blank?
            = image_tag("/assets/default.jpg")
          - else
            = image_tag(current_user.avatar.url)   
          .first-child
            = "Welcome #{current_user.first_name}"
            %br
            %span
              = link_to('Edit account', edit_user_registration_path)
        .divider
        %h3 Collect
        %ul.nav.nav-pill.nav-stacked
          %li.active
            %i.icon-inbox= link_to('INBOX',"#{tasks_path}?key=inbox")
            .badge.pull-right.inbox= current_user.nodes.where(action: 'Inbox').count - 1
          %h3 Control panel  
          %li
            %i.icon-inbox= link_to('Next',"#{tasks_path}?key=next")
            .badge.pull-right.next= current_user.nodes.where(action: 'Next').count   
          %li
            %i.icon-inbox= link_to('Project',"#{tasks_path}?key=project")
            .badge.pull-right.project= current_user.nodes.where(action: 'Project').count  
          %li
            %i.icon-inbox= link_to('Waiting',"#{tasks_path}?key=waiting")
            .badge.pull-right.waiting= current_user.nodes.where(action: 'Waiting').count  
          %li
            %i.icon-inbox= link_to('Someday',"#{tasks_path}?key=someday")
            .badge.pull-right.someday= current_user.nodes.where(action: 'Someday').count 
          %li.divider
          %h3 Cleanup
          %li
            %i.icon-book= link_to('Logbook',"#{tasks_path}?key=logbook")
            .badge.pull-right.logbook= current_user.nodes.where(action: 'Logbook').count
          %li
            %i.icon-inbox= link_to('Trash',"#{tasks_path}?key=trash")
            .badge.pull-right.trash= current_user.nodes.where(action: 'Trash').count 
            .pull-right= link_to 'CLEAR', trash_task_path,method: :delete, data: { confirm: 'Are you sure?' }            
        %h3 Search panel
        = render 'filter/form' 
    %li.span9.pull-right.sidebar
      %h1.page-header Work Desk
      .class.alert.adjusted.alert-info
        %button.close{:type => "button", "data-dismiss" => "alert"} x
        %i.cus-exclamation
        %strong Welcome to Work Desk Please don't forget to check out  all the task and project
      %ul.nav.nav-tabs#myTab
        %li.active
          %a{:href=>"#inbox", :"data-toogle"=>"tab"}
            %i.icon-inbox=   params[:key] ? params[:key].upcase : 'ALL TASKS' 
        %li
          %a{:href=>"#calendar", :"data-toogle"=>"tab"}
            %i.icon-calendar CALENDAR 
        %li
          %a{:href=>"#statistics", :"data-toogle"=>"tab"} STATISTICS
      .thumbnail
        .tab-content#myTabContent
          .tab-pane.fade.active.in#inbox
            - hidden = "display:none" 
            = #link_to 'CLEAR', '#', style: hidden
            .sidebar(style="display:inline")
              %ol.sortable_tree{ data: { max_levels: 5, rebuild_url: rebuild_nodes_url } }
                .state= render 'tree' 
          .tab-pane.fade#calendar
            = link_to('New Event', '#NewtaskModal', data: { toggle: 'modal' } )
            .calendar= render 'calendar'  
                      
                      
          .tab-pane.fade#statistics
            .header-edit 
              %h2 Total productive and unproductive time
            .thumbnail
              = include_gon 
              #piechart{style:"width: 900px; height: 500px"}
              
  = render 'projects/form' 
  = render 'form'
  = render 'interruptions/form' 

        

app/views/tasks/new.html.haml
%h1 New task

= render 'form' 

= link_to 'Back', tasks_path 

app/views/tasks/show.html.haml
%p#notice= notice 
.thumbnail
  .caption
    %p
      %b Task:
      = @task.task_name 

    %p
      %b Due date:
      = @task.due_date

    %p
      %b Priority:
      = @task.priority 

    %p
      %b Note:
      = @task.note 

    %p
      %b duration unproductive time :
      - suma = 0.0
      - @task.interruptions.where('interruptions.duration IS NOT NULL  ').each do |valor|
        - suma = suma + valor.duration  
      = suma

    %p
      %b duration productive time:
      -if current_user.total_time != 0.0
        = current_user.total_time += (@task.finish_time - @task.start_time)
      -else
        =current_user.total_time = 0.0

= link_to 'Edit', edit_task_path(@task)  |
= link_to 'Back', tasks_path 