config/routes.rb
 Prototype::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => 'tasks#index'
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :sessions => "users/sessions", registrations: "users/registrations" }
  

  resources :projects
  resources :tasks do
    get '/start_task' => "tasks#start", :as => :start_task
    get '/finish_task' => "tasks#finish", :as => :finish_task

    
    resources :interruptions
    post '/interruptions' => "interruptions#create", :as => :create_interruption
    get  '/interruptions_stop'=> "interruptions#stop_interruption", :as => :stop_interruption
  end   
  get '/state_task' => "tasks#state", :as => :state_task
  delete '/trash_task' => "tasks#trash", :as => :trash_task
  get '/reload_month' => "tasks#reload_month", :as => :reload_month
  get '/reload_tree' => "tasks#reload_tree", :as => :reload_tree
  

   
   resources :nodes do
    collection do
      get :manage

      post :rebuild
    end
   end 

end

app/models/project.rb
class Project < Node
  include ActiveModel::ForbiddenAttributesProtection
  validates :project_title, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'application'
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find(params[:id])
    @task = Task.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @parent = current_user.projects.first
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.nodes.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.create(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to "http://localhost:3000/tasks", notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
  def project_params
    params.require(:project).permit(:project_title, :parent_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.modal.hide.fade#NewprojectModal
  .modal-header
    %button.close(data-dismiss="modal" aria-hidden="true") &times
    %h1
  .modal-body
    = simple_form_for(@project) do |f| 
      - if @project.errors.any? 
        #error_explanation
          %h2
            = pluralize(@project.errors.count, "error")  
            prohibited this project from being saved:

          %ul
          -@project.errors.full_messages.each do |msg| 
            %li = msg  
      
      .field= f.input :project_title 
      .field= f.select :parent_id, nested_set_options(current_user.projects, nil, method: :type, value: 'Task') {|i| "#{'-' * i.level} #{i.project_title}"  if i.type == 'Project' } 
      .modal-footer  
        .actions= f.submit      

app/views/projects/edit.html.haml
.header-edit 
  %h2 Editing project
.thumbnail
  .caption
    = simple_form_for(@project) do |f|
      .field= f.input :project_title 
      .field= f.select :parent_id, nested_set_options(current_user.projects, nil, method: :type, value: 'Task') {|i| "#{'-' * i.level} #{i.project_title}"  if i.type == 'Project' } 
      .actions= f.submit 

= link_to 'Show', @project  |
= link_to 'Back', "http://localhost:3000/tasks" 

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Title
    %th
    %th
    %th

- @projects.each do |project| 
  %tr
    %td= project.project_title 
    %td= link_to 'Show', project 
    %td= link_to 'Edit', edit_project_path(project) 
    %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } 
    %br 

= link_to 'New Project', new_project_path 
= link_to 'Back', tasks_path 

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', tasks_path 

app/views/projects/show.html.haml
%p#notice= notice
.thumbnail
  .caption
    %p
      %b Title:
      = @project.project_title 

    = select_tag 'parent_id', options_for_select(nested_set_options(current_user.projects, nil, method: :type, value: 'Task') {|i| "|#{'-' * i.level} #{i.project_title}" } ) 



= link_to 'Edit', edit_project_path(@project)  |
= link_to 'Back', tasks_path  